version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - api-gateway
  nginx:
    build: .
    ports:
      - "8080:8080"
    networks:
      - api-gateway
  echo:
    image: "gsdenys/echo:v1.0"
    ports:
      - "3000:3000"
    networks:
      - api-gateway
networks:
  api-gateway:
    # driver: bridge